
const toolbar_items = [
  {
    name: '按钮',
    tag: 'el-button',
    tool: 'ButtonToolBar',
    width: 90,
    height: 40,
    text: '按钮',
    inner_text: true,
    props: { type: '' },
  },
  {
    name: '文本',
    tag: 'div',
    tool: 'ButtonToolBar',
    width: 70,
    height: 20,
    text: '文本',
    inner_text: true,
    props: {},
  },
  {
    name: '输入框',
    tag: 'el-input',
    tool: 'ButtonToolBar',
    width: 150,
    height: 40,
    text: '',
    inner_text: false,
    props: { placeholder: '' },
  },
  {
    name: '单选框',
    tag: 'el-radio',
    tool: 'ButtonToolBar',
    width: 70,
    height: 20,
    text: '单选框',
    inner_text: true,
    props: { 'v-model': '' },
  },
  {
    name: '多选框',
    tag: 'el-checkbox',
    tool: 'ButtonToolBar',
    width: 70,
    height: 20,
    text: '多选框',
    inner_text: true,
    props: {},
  },
  {
    name: '计数器',
    tag: 'el-input-number',
    tool: 'ButtonToolBar',
    width: 150,
    height: 40,
    text: '',
    inner_text: false,
    props: {},
  },
  {
    name: '选择器',
    tag: 'el-select',
    tool: 'ButtonToolBar',
    width: 150,
    height: 40,
    text: '',
    inner_text: false,
    props: { placeholder: '' },
  },
  {
    name: '开关',
    tag: 'el-switch',
    tool: 'ButtonToolBar',
    width: 50,
    height: 30,
    text: '',
    inner_text: false,
    props: { 'active-color': '#13ce66', 'inactive-color': '#ff4949' },
  },
  {
    name: '滑块',
    tag: 'el-slider',
    tool: 'ButtonToolBar',
    width: 150,
    height: 40,
    text: '',
    inner_text: false,
    props: {},
  },
  {
    name: '评分',
    tag: 'el-rate',
    tool: 'ButtonToolBar',
    width: 140,
    height: 20,
    text: '',
    inner_text: false,
    props: {},
  },
  {
    name: '卡片',
    tag: 'el-card',
    tool: 'ButtonToolBar',
    width: 200,
    height: 200,
    text: '卡片',
    inner_text: true,
    props: {},
  },
];

export default toolbar_items;
