const toolbar_items = [
  {
    name: '按钮',
    tag: 'el-button',
    tool: 'ButtonToolBar',
    width: 90,
    height: 40,
    text: '按钮',
    inner_text: true,
    props: { type: '' },
    child_tag: '',
    child_props: [],
  },
  {
    name: '文本',
    tag: 'div',
    tool: '',
    width: 70,
    height: 20,
    text: '文本',
    inner_text: true,
    props: {},
    child_tag: '',
    child_props: [],
  },
  {
    name: '输入框',
    tag: 'el-input',
    tool: 'InputToolBar',
    width: 150,
    height: 40,
    text: '',
    inner_text: false,
    props: { placeholder: '' },
    child_tag: '',
    child_props: [],
  },
  {
    name: '计数器',
    tag: 'el-input-number',
    tool: '',
    width: 150,
    height: 40,
    text: '',
    inner_text: false,
    props: {},
    child_tag: '',
    child_props: [],
  },
  {
    name: '单选框',
    tag: 'el-radio-group',
    tool: 'RadioToolBar',
    width: 120,
    height: 20,
    text: '',
    inner_text: false,
    props: {},
    child_tag: 'el-radio',
    child_props: [{ label: '单选框' }], // [{label}]
  },
  {
    name: '多选框',
    tag: 'el-checkbox',
    tool: '',
    width: 70,
    height: 20,
    text: '多选框',
    inner_text: true,
    props: {},
    child_tag: '',
    child_props: [],
  },
  {
    name: '下拉选择器',
    tag: 'el-select',
    tool: 'SelectToolBar',
    width: 150,
    height: 40,
    text: '',
    inner_text: false,
    props: { placeholder: '' },
    child_tag: 'el-option',
    child_props: [], // {value}
  },
  {
    name: '开关',
    tag: 'el-switch',
    tool: '',
    width: 50,
    height: 30,
    text: '',
    inner_text: false,
    props: { 'active-color': '#13ce66', 'inactive-color': '#ff4949' },
    child_tag: '',
    child_props: [],
  },
  {
    name: '滑块',
    tag: 'el-slider',
    tool: '',
    width: 150,
    height: 40,
    text: '',
    inner_text: false,
    props: {},
    child_tag: '',
    child_props: [],
  },
  {
    name: '评分',
    tag: 'el-rate',
    tool: '',
    width: 140,
    height: 20,
    text: '',
    inner_text: false,
    props: {},
    child_tag: '',
    child_props: [],
  },
  {
    name: '卡片',
    tag: 'el-card',
    tool: '',
    width: 200,
    height: 200,
    text: '卡片',
    inner_text: true,
    props: {},
    child_tag: '',
    child_props: [],
  },
];

export default toolbar_items;
